activity_action = {
    "handbag_shoulder_left_activity_step": "location",
    "front_right_pocket_activity_step": "location",
    "back_right_pocket_activity_step": "location",
    "jacket_outer_left_pocket_activity_step": "location",
    "holding_right_hand_activity_step": "location",
    "handbag_hand_left_activity_step": "location",
    "landscape_texting_activity_step": "interaction",
    "backpack_activity_step": "location",
    "jacket_outer_right_pocket_activity_step": "location",
    "handbag_shoulder_right_activity_step": "location",
    "recording_voice_message_activity_step": "interaction",
    "front_left_pocket_activity_step": "location",
    "handbag_hand_right_activity_step": "location",
    "jacket_breast_pocket_activity_step": "location",
    "texting_activity_step": "interaction",
    "reading_watching_activity_step": "interaction",
    "holding_left_hand_activity_step": "location",
    "telephoning_activity_step": "interaction",
    "jacket_inner_pocket_activity_step": "location",
    "back_left_pocket_activity_step": "location",
    "sample_task_activity_step": "interaction",
    "listening_voice_message_activity_step": "interaction",
    "satchel_diagonal_right_activity_step": "location",
    "satchel_shoulder_right_activity_step": "location",
    "reading_scrolling_activity_step": "interaction"
}